canal.ip = 0.0.0.0
canal.port = 11111
canal.metrics.pull.port = 11112
canal.zkServers =
canal.serverMode = tcp
canal.destinations = example
canal.conf.dir = /home/admin/canal-server/conf
canal.file.data.dir = /home/admin/canal-server/conf
canal.instance.global.mode = spring
canal.instance.global.lazy = false
canal.instance.global.spring.xml = classpath:spring/memory-instance.xml
canal.auto.reset.latest.pos.mode = never
